### PR TITLE
Improve getServer

### PR DESCRIPTION
**Pull request by Hazerdous**
Shrinking the getServer command, as well as using more efficient code

### CODE REVIEW

**Comment by piks** [comment]
suprized this wasnt done sooner... good job XD

**Comment by cellsheet** [comment]
says the current maintainer :P

**Comment by piks** [comment]
@cellsheet yep XD

**Comment by danielisaksen** [comment]
@Hazerdous' syntax is really messy though. He should take another cleanup and properly fix his code. :)

**Pull request merged**
