### PR TITLE
Fix early update pid digest events

### LINKED ISSUE #40: bot is skipping messages
I am using this for getting messages from a group.
I am opening the script output window and the group opened in a browser.
I have noticed that it is skipping some messages.
Please ping me if any other info is required to fix this. I am also looking for exact cause.
Thanks.

### PR DESCRIPTION
**Pull request by james-d-elliott**
- Added pidDict storing kv pair of pnum: pid
- Handle early u digest with:
  - Adding to pidDict when u digest occurs early
  - Checking pidDict when b digest occurs and using and removing it
  - DUPLICATED code from u digest to b digest

Fixes #40

### CODE REVIEW

**Comment by james-d-elliott** [comment]
Just a note, this has NOT been tested, though should work or give you a method to work on #40.

**Comment by sooqua** [comment]
Throws an exception: NameError: name 'user' is not defined

**Comment by piks** [comment]
Oops, thought I had commented on this when it was made, this would indeed fix the invalid UID problem, however chatango doesn't always send a UID along with a post (not sure why), implementing this change would stop any posts that never obtain a UID from ever being emmited. Not sure if that would be good or not for current bots running the lib. I agree with the change, what do you think @cellsheet @Hazerdous

**Comment by piks** [comment]
Going to run tests with this and see just how many posts are lost, if its not too much then I'll merge it.

**Comment by james-d-elliott** [comment]
There are additional ways to get around that problem (always emit command event on b events and just use the u events for updating if the post exists), though I've never seen a completely dropped u event, just a delayed one. My bots use a similar method to this and always reply to commands and see messages.

**Comment by piks** [comment]
Thanks for fixing, however user is still undefined. @james-d-elliott

**Pull request closed without merging**
